"""initial schema

Revision ID: 1302886e18bc
Revises: 
Create Date: 2026-10-03 20:12:18.470699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1302886e18bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('email_from', sa.String(length=255), nullable=False),
    sa.Column('email_from_name', sa.String(length=255), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=False),
    sa.Column('physical_address', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password', sa.String(length=255), nullable=False),
    sa.Column('smtp_tls', sa.Boolean(), nullable=True),
    sa.Column('daily_email_limit', sa.Integer(), nullable=True),
    sa.Column('emails_sent_today', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_account_email'), ['account_email'], unique=True)

    op.create_table('automations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_value', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('workflow', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.create_index('idx_automation_business_trigger', ['business_id', 'trigger_type', 'status'], unique=False)

    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_line', sa.String(length=500), nullable=False),
    sa.Column('preview_text', sa.String(length=255), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('template_variables', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_template_business_name')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_business_id'), ['business_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filter_rules', sa.JSON(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('count_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_segment_business_name')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_business_id'), ['business_id'], unique=False)

    op.create_table('subscribers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('total_opens', sa.Integer(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.Column('last_clicked_at', sa.DateTime(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email', name='uq_subscriber_business_email')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index('idx_subscriber_business_status', ['business_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_email'), ['email'], unique=False)

    op.create_table('automation_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('automation_id', sa.String(length=36), nullable=False),
    sa.Column('subscriber_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('waiting_step', sa.Integer(), nullable=True),
    sa.Column('last_email_log_id', sa.String(length=36), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_instances', schema=None) as batch_op:
        batch_op.create_index('idx_automation_instance_due', ['status', 'next_run_at'], unique=False)
        batch_op.create_index('idx_automation_instance_sub', ['automation_id', 'subscriber_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject_line', sa.String(length=500), nullable=True),
    sa.Column('subject_variants', sa.JSON(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_opens', sa.Integer(), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('total_bounces', sa.Integer(), nullable=True),
    sa.Column('total_unsubscribes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_business_status', ['business_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_scheduled_time'), ['scheduled_time'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('automation_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('subscriber_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject_line', sa.String(length=500), nullable=True),
    sa.Column('subject_variant', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('bounce_type', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index('idx_email_log_business_campaign', ['business_id', 'campaign_id'], unique=False)
        batch_op.create_index('idx_email_log_status_next_attempt', ['status', 'next_attempt_at'], unique=False)
        batch_op.create_index('idx_email_log_subscriber_status', ['subscriber_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_sent_at'), ['sent_at'], unique=False)

    op.create_table('email_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('email_log_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('subscriber_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_log_id'], ['email_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index('idx_email_event_business_type', ['business_id', 'event_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_email_log_id'), ['email_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_subscriber_id'), ['subscriber_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_email_log_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_campaign_id'))
        batch_op.drop_index('idx_email_event_business_type')

    op.drop_table('email_events')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_sent_at'))
        batch_op.drop_index('idx_email_log_subscriber_status')
        batch_op.drop_index('idx_email_log_status_next_attempt')
        batch_op.drop_index('idx_email_log_business_campaign')

    op.drop_table('email_logs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_scheduled_time'))
        batch_op.drop_index('idx_campaign_business_status')

    op.drop_table('campaigns')
    with op.batch_alter_table('automation_instances', schema=None) as batch_op:
        batch_op.drop_index('idx_automation_instance_sub')
        batch_op.drop_index('idx_automation_instance_due')

    op.drop_table('automation_instances')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_email'))
        batch_op.drop_index('idx_subscriber_business_status')

    op.drop_table('subscribers')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_business_id'))

    op.drop_table('segments')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_business_id'))

    op.drop_table('email_templates')
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_index('idx_automation_business_trigger')

    op.drop_table('automations')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_account_email'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
